//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uasmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kamar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kamar()
        {
            this.reservasi = new HashSet<reservasi>();
        }
    
        public int KamarID { get; set; }
        public string no_kamar { get; set; }
        public string nama_kamar { get; set; }
        public decimal harga_kamar { get; set; }
        public string status_kamar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservasi> reservasi { get; set; }
    }
}
