//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uasmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uasEntities : DbContext
    {
        public uasEntities()
            : base("name=uasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kamar> kamar { get; set; }
        public virtual DbSet<pelanggan> pelanggan { get; set; }
        public virtual DbSet<pembayaran> pembayaran { get; set; }
        public virtual DbSet<reservasi> reservasi { get; set; }
    }
}
