//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uasmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pelanggan()
        {
            this.reservasi = new HashSet<reservasi>();
        }
    
        public int PelangganID { get; set; }
        public string ktp_pelanggan { get; set; }
        public string nama_pelanggan { get; set; }
        public string email_pelanggan { get; set; }
        public string telp_pelanggan { get; set; }
        public string alamat_pelanggan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservasi> reservasi { get; set; }
    }
}
